### PR TITLE
Modified persistentId to allow an object, for the case in python where the id is a tuple

### PR DESCRIPTION
**Pull request by shaltielshmid**
I've encountered a case when unpickling a file in C# where the persistentId is actually a tuple of items, and then when the function is called it just gets a string "System.Object[]" instead of the contents of the object.

### CODE REVIEW

**Comment by irmen** [comment]
Can you provide such a pickle file? I don't think I've seen one like that before.

Also, are you perhaps able to change the Java version as well, to keep in sync?

**Comment by shaltielshmid** [comment]
Generally, the library `PyTorch` return a tuple for the persistentId when using `torch.save`. 

For an example, you can find one on the official pickle documentation page [here](https://docs.python.org/3/library/pickle.html?highlight=persistent#persistence-of-external-objects). Their example uses a tuple as the persistentId.

**Comment by shaltielshmid** [comment]
Also, I'm adding another feature to allow for persistentId when pickling, I should update the PR soon.

**Comment by shaltielshmid** [comment]
Updated PR summary:

- Modified persistentLoad to accept an object instead of a string, to allow for complex type ids. 
- Added a persistentId virtual function in pickler to allow using persistentIds when pickling. 
- Added an object deconstructor type, to allow serializing custom classes (the opposite of IObjectConstructor in unpickling). Technically this can be implemented as a custom pickler (using IObjectPickler), but I thought it would be cleaner if one doesn't have to deal with the opcodes in downstream code.

**Comment by shaltielshmid** [comment]
Update:
- Added unit tests
- Added implementation in Java + added unit tests as well

**Comment by irmen** [comment]
Thanks for working on this, I'll have a look soon

**Comment by shaltielshmid** [comment]
Hi @irmen , haven't heard from you in a few days. Wanted to check in about this PR, is there anything I can do to help merge it in?

**Comment by irmen** [comment]
Sorry I haven't found some time to actually review this yet. Will attempt to do so before the end of the week.

**Comment by irmen** [comment]
Looking good! Thank you for the contribution.

**Comment by shaltielshmid** [comment]
@irmen Thanks for merging! I saw you updated the version number to 1.5.0 - when do you think you'll upload the new version to NuGet? 

Thanks!

**Comment by irmen** [comment]
done

**Comment by shaltielshmid** [comment]
Thanks!

**Comment by mullerhai** [comment]
@irmen  java also need pickle load save pytorch model,

**Comment by mullerhai** [comment]
I want to do more for pickle on scala3

**Comment by irmen** [comment]
Please don't resurrect an super old pull request comment section for unrelated stuff.
That said, you can write a custom class serializer and deserializer and register those to the library using registerConstructor()   and registerCustomPickler()  methods

**Pull request merged**
